/**
 * Valid languages for interpreter profiles
 * This ensures data integrity and prevents invalid entries
 */
export const VALID_LANGUAGES = [
  "English",
  "Spanish",
  "Mandarin Chinese",
  "French",
  "Arabic",
  "Portuguese",
  "Russian",
  "Japanese",
  "German",
  "Korean",
  "Italian",
  "Vietnamese",
  "Tagalog",
  "Polish",
  "Hindi",
  "Urdu",
  "Bengali",
  "Punjabi",
  "Tamil",
  "Telugu",
  "Marathi",
  "Gujarati",
  "Kannada",
  "Malayalam",
  "Thai",
  "Turkish",
  "Dutch",
  "Swedish",
  "Greek",
  "Czech",
  "Romanian",
  "Hungarian",
  "Hebrew",
  "Ukrainian",
  "Persian (Farsi)",
  "Amharic",
  "Swahili",
  "Yoruba",
  "Hausa",
  "Somali",
  "Afrikaans",
  "Zulu",
  "Xhosa",
  "Indonesian",
  "Malay",
  "Burmese",
  "Khmer",
  "Lao",
  "Nepali",
  "Sinhala",
  "Pashto",
  "Kurdish",
  "Albanian",
  "Serbian",
  "Croatian",
  "Bosnian",
  "Bulgarian",
  "Macedonian",
  "Slovak",
  "Slovenian",
  "Lithuanian",
  "Latvian",
  "Estonian",
  "Finnish",
  "Danish",
  "Norwegian",
  "Icelandic",
  "Irish",
  "Welsh",
  "Basque",
  "Catalan",
  "Galician",
  "Armenian",
  "Georgian",
  "Azerbaijani",
  "Kazakh",
  "Uzbek",
  "Turkmen",
  "Mongolian",
  "Tibetan",
  "American Sign Language (ASL)",
  "Other",
] as const;

/**
 * US States (2-letter codes)
 */
export const US_STATES = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
  { code: "DC", name: "District of Columbia" },
  { code: "PR", name: "Puerto Rico" },
] as const;

/**
 * Common countries for international interpreters
 */
export const COUNTRIES = [
  "USA",
  "Canada",
  "Mexico",
  "Brazil",
  "United Kingdom",
  "France",
  "Germany",
  "Spain",
  "Italy",
  "Portugal",
  "Netherlands",
  "Belgium",
  "Switzerland",
  "Austria",
  "Poland",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Greece",
  "Turkey",
  "Russia",
  "Ukraine",
  "China",
  "Japan",
  "South Korea",
  "India",
  "Pakistan",
  "Bangladesh",
  "Philippines",
  "Indonesia",
  "Thailand",
  "Vietnam",
  "Malaysia",
  "Singapore",
  "Australia",
  "New Zealand",
  "South Africa",
  "Egypt",
  "Nigeria",
  "Kenya",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "Venezuela",
  "Other",
] as const;

/**
 * Proficiency levels
 */
export const PROFICIENCY_LEVELS = [
  "Native",
  "Fluent",
  "Advanced",
  "Intermediate",
  "Basic",
] as const;

/**
 * Certification types
 */
export const CERTIFICATION_TYPES = [
  "Court Certified",
  "Medical Certified",
  "Federal Certified",
  "State Certified",
  "Conference Interpreter",
  "Community Interpreter",
  "Legal Interpreter",
  "Healthcare Interpreter",
  "Educational Interpreter",
  "Business Interpreter",
  "None",
] as const;
